version: '3'
services:
  app:
    build: ./
    ports:
      - "3007:3007"
    expose:
      - 3007
    volumes:
      - ./:/app
      - /app/node_modules
    container_name: react-charts
    env_file:
      - ./.env